### ISSUE TITLE
tootalcomand插件新建几个命令

### ISSUE THREAD

**Issue by avkiller** [linxinhong/VimDesktop#3]
目前每次更新以后都需要从老插件中复制过来,希望能够原生支持

;<SearchStandalone>: >>搜索文件{{{2
<SearchStandalone>:
    SendPos(545)
Return

; <GoDesktop>
<GoDesktop>:
        ControlSetText, %TCEdit%, cd %A_Desktop%, ahk_class  TTOTAL_CMD
        ControlSend,%TCEdit%,  {Enter}, ahk_class TTOTAL_CMD
Return

; <CopyNameOnly> {{{1
<CopyNameOnly>:
        CopyNameOnly()
Return
CopyNameOnly()
{
    clipboard :=
    GoSub,<cm_CopyNamesToClip>
    ClipWait
    If Not RegExMatch(clipboard,"^.._")
        clipboard := RegExReplace(RegExReplace(clipboard,"\$"),".[^.]_$")
}

**Comment by linxinhong** [comment]
1. 搜索文件使用的 <cm_SearchStandalone>，已添加。
2. 切换到桌面功能，增加<TC_GotoDesktop>。
3. 仅复制文件名，请使用<cm_CopyNamesToClip>。

请下载最新版本。

**Comment by avkiller** [comment]
3 仅复制文件名，请使用。

 这个是什么?

**Comment by avkiller** [comment]
1 使用<cm_CopyNamesToClip> 复制的是totalcmd.ahk

2 之前的viatc里面可以直接使用CopyNameOnly 复制得到totalcmd (即不要后缀名)

**Comment by ArrayHotkey** [comment]
哦，明白。。 下一版添加

**Comment by linxinhong** [comment]
已经添加 <TC_CopyNameNoExt>

**Comment by avkiller** [comment]
1. <TC_CopyNameNoExt>
    已经测试ok
2. <cm_SearchStandalone>
    已经测试ok
3. <TC_GotoDesktop>
   已经测试ok

辛苦owner了
